### PR TITLE
Fix styling regression on print media - chromium

### LINKED ISSUE #444: styling regression on print media
We seam to have a styling regression in post 0.0.22 versions.
print_style

The printed page should not have a left margin that big.

### PR DESCRIPTION
**Pull request by Listwon**
Fixes #444

### CODE REVIEW

**Comment by Listwon** [comment]
Hi @budziq! I've just tested this on Chrome. Have you tried to rebuild example book with rebuilt mdBook? Or maybe I just don't understand where this bug persists :) 
mdbook_print

**Comment by budziq** [comment]
Ok I think I've got the root cause.

The print output looks exactly as expected when the sidebar is hidden.
good_print

While when its shown prior to triggering the print dialog.
bad_print

**Comment by Listwon** [comment]
Oh, I've just reproduced it. Thanks for the hint!

**Comment by Listwon** [comment]
@budziq please test it now :)

**Comment by budziq** [comment]
Merged! Thanks a lot @Listwon! :+1:

**Pull request closed without merging**
