### PR TITLE
Add anchors around all headers in the content.

### PR DESCRIPTION
**Pull request by asolove**
This is one way to address #72, creating anchors for sections in the text.

- Just uses the header's text as its anchor name. Spaces in the names work fine in URLs. In the browsers I tested, scrolling to the anchor in the URL works even when the anchor is added after the DOM loads.
- Adjust theme css to only style links, not <a> tags used as anchors.

### CODE REVIEW

**Comment by azerupi** [comment]
You changed the CSS file directly, but I use [stylus](http://stylus-lang.com/) (css pre-processor) to have more modular stylesheets. The stylesheet is added to the git repo so that people don't have to install node.js to regenerate it.

Would you mind editing the [stylus files](https://github.com/azerupi/mdBook/tree/master/src/theme/stylus) instead?  

>scrolling to the anchor in the URL works even when the anchor is added after the DOM loads.

I never thought that would work, but if it does, everything else is good. I will merge once you change the stylus files :wink:

**Comment by asolove** [comment]
Oh, hah, didn't even see them. Yeah, I'll update this a little later today.

**Comment by azerupi** [comment]
Sure I will merge it tomorrow morning then (time-zone difference UTC+01:00 here :wink: )

**Comment by steveklabnik** [comment]
:confetti_ball:

**Comment by azerupi** [comment]
Perfect, merging now!

**Pull request merged**
