### PR TITLE
mdbook test documentation

### PR DESCRIPTION
**Pull request by steveklabnik**
Part of https://github.com/azerupi/mdBook/issues/80

Feel free to not take the second commit; I don't know if you want to bother testing the book, but figured I'd give it a shot :)

### CODE REVIEW

**Comment by azerupi** [comment]
Nice! Thanks :)

**Comment by steveklabnik** [comment]
Any time :) 

BTW, when do you plan on doing the next release? Excited about all the stuff that's been landing :smile:

**Comment by azerupi** [comment]
Soon! I just want to resolve #70 because it really doesn't look that good at the moment, and then I upload :wink:

**Comment by azerupi** [comment]
I got it resolved, so I will probably upload tomorrow  :tada:

**Pull request merged**
