### PR TITLE
Implement Serve feature

### PR DESCRIPTION
**Pull request by Bobo1239**
I'm new to Rust so the code is probably not optimal. Please bear with me. I'm open to suggestions/improvements.

- In `livereload.rs`: the websocket server isn't able to handle [Ping/Pong](https://tools.ietf.org/html/rfc6455#section-5.5.2) messages atm. I tried to make a `MessageType.Ping(Box<Message>)` but wasn't able to figure out how to deal with the lifetimes.
- The `ComparableSender(Factory)` stuff feels pretty hacky... Suggestions?

### CODE REVIEW

**Comment by Bobo1239** [comment]
[rust-websocket](https://github.com/cyderize/rust-websocket) currently has no option to disable ssl support. We can either try to change that upstream (didn't look at it yet) or switch to another websocket library (e.g. [ws-rs](https://github.com/housleyjk/ws-rs)).

**Comment by azerupi** [comment]
Woah this is awesome! 

It will take me some time to review this because I am not very familiar with the dependencies and it's a pretty substantial contribution ;)

>rust-websocket currently has no option to disable ssl support. We can either try to change that upstream (didn't look at it yet) or switch to another websocket library (e.g. ws-rs).

That is the cause of the failed tests, right? 
Maybe this is something we could ask on [users.rust-lang.org](https://users.rust-lang.org/) to get feedback of people who have already tried some of them.

**Comment by Bobo1239** [comment]
Ok, [ws-rs](https://github.com/housleyjk/ws-rs) has ssl support as an optional feature and provides a `broadcaster` function which allows the whole livereload stuff to be reduced to 20 LOC...

**Comment by azerupi** [comment]
I just tested this locally and it seems to work very well. It is amazingly useful and will surely be a huge time saver for a lot of people! :+1: 

There is just one small thing, when you stop serving, the code for the web-socket is still present in the rendered files. It's really no biggie and it can be resolved by just doing a `mdbook build`, but improving this could be an idea for a future improvement :wink:

Anyway, very good job with this

**Comment by jgillich** [comment]
@azerupi Can you push an update to crates.io? :)

**Comment by azerupi** [comment]
Yes I'll do that right now :)

**Pull request merged**
