### PR TITLE
Add navigation by keyboard using alt + left/right arrows

### PR DESCRIPTION
**Pull request by funkill**
Add navigation to next and previous pages by 'alt + &rarr;' and 'alt + &larr;' combinations. Issue #81 with modification (add alt key)

### CODE REVIEW

**Comment by azerupi** [comment]
I know that sometimes people have trouble with non-english keyboards when using hardcoded keycodes. I don't expect `alt` and `arrows` to cause trouble though. Have you tested it with different keyboards?

I have an Azerty keyboard, so I will let you know if it works fine here.

Thanks a lot for the Pull Request! :smile:

**Comment by azerupi** [comment]
Sorry, I merged too quickly. This causes some trouble with the `Go back` and `Go forward` page navigation in Google Chrome.

**Comment by funkill** [comment]
I tested in russian keyboard, all works. 
About back/forward navigation: now i tests in firefox, he has same behavior. I often use `backspace` for previous page and dont known about `alt-arrow` combinations :smile: 
I think if use only one key, we have some trouble with errors key press. What are you think about possible combinations?

**Comment by azerupi** [comment]
Yeah arrows could be pressed by mistake, but I don't think it would be that problematic.

On Chrome, both `ctrl` and `shift` combined with the arrow keys don't seem to do anything. Shift seems to me like the safest modifier key, but it's not very intuitive. `ctrl` would have to be tested on mac, to see if it stays `ctrl` as they use `command`. 

I would just bind to the arrow keys without modifier, if we get negative feedback it can easily be changed later. What do you think?

**Comment by funkill** [comment]
Combination of `ctrl` and `shift` can be used for change keyboard layout (e.g. on Windows use `shift+alt` for change english and other layouts, some people change it combination to `ctrl+shift`).
Only arrow: why not?

**Comment by funkill** [comment]
Are need some help message in title for shortcuts (e.g. For see next page, you can use `->` key) or only character?

**Comment by azerupi** [comment]
Yeah I will add a help icon on the menu-bar in the future to spawn a help popup. If you want you can add a tooltip on the navigation arrows for now.

**Pull request merged**
