### PR TITLE
travis: test/release on/for i686-apple-darwin

### PR DESCRIPTION
**Pull request by japaric**
I think this should do it.

r? @azerupi

### CODE REVIEW

**Comment by japaric** [comment]
`fsevent-sys` is broken on `i686-apple-darwin`. I sent a patch (octplane/fsevent-rust#7), but it will take a while to reach `rsnotify` so I'm going to close this until that happens.

**Comment by azerupi** [comment]
Sure, no problem :)

**Comment by japaric** [comment]
`fsevent-sys` got a new release, let's see if this works now.

**Comment by japaric** [comment]
@azerupi This should be good to go now.

**Comment by azerupi** [comment]
Sorry, I was not home when I read the notification and forgot about it :blush: 

Many thanks!

**Pull request merged**
