### PR TITLE
Change key for theme to not clobber old books

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes https://github.com/azerupi/mdBook/issues/448

Is this the path we want to take? It sucks to choose a different key, but it's an easy fix, and not *that* bad.

What about the `sidebar` key?

### CODE REVIEW

**Comment by azerupi** [comment]
Is this really needed? Can't we find a way to go back to the value without quotes? 
I assume that store.js is doing this. Would there be a way to disable that behavior? Before merging this PR adding prefixes, I would like to see if there isn't another way to solve this issue. The ideal fix would be to revert to using the unquoted value.

**Comment by budziq** [comment]
@azerupi I'm guessing that the quoting comes from the fact that store.js actually serializes/deserializes complex objects into local storage as strings.

**Comment by azerupi** [comment]
Yes, I just found that out too. Store.js calls [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) internally, inserting quotes in the strings. There doesn't seem to be much we can do about it.

Actually, now that I think about it a bit more, prefixing might actually be the right move. Because localstorage is per domain and our keys might clash with other scripts using localstorage on the same domain.

**Comment by steveklabnik** [comment]
> Is this really needed? Can't we find a way to go back to the value without quotes?
I assume that store.js is doing this. Would there be a way to disable that behavior? Before merging this PR adding prefixes, I would like to see if there isn't another way to solve this issue. The ideal fix would be to revert to using the unquoted value.

All these are good questions, which is why I wanted to start a discussion 😄 

It's basically "is it simpler to customize store.js, or is it simpler to namespace a key?" The latter seems cleaner to me overall, but I could be convinced, I guess.

**Comment by budziq** [comment]
I'm no webdev but judging from the fact that localstorage is a shared for the whole domain. I would go for some namespacing anyway.

**Comment by steveklabnik** [comment]
@budziq updated!

Is there any chance we can cut a release for this sometime soon?

**Pull request merged**
