### PR TITLE
Hide theme selection popup after interaction

### PR DESCRIPTION
**Pull request by budziq**
fixes https://github.com/azerupi/mdBook/issues/330

### CODE REVIEW

**Comment by budziq** [comment]
Both commits are orthogonal so I can drop the first one.

**Comment by azerupi** [comment]
>Both commits are orthogonal so I can drop the first one.

I think that would be best. If in the future we do find we want it anyway, we can still add it later.

**Comment by budziq** [comment]
done :)

**Comment by azerupi** [comment]
Thanks!

**Pull request merged**
