### PR TITLE
handle play.rust-lang.org communication errors in playpens

### PR DESCRIPTION
**Pull request by budziq**
also add 15s communication timeout

fixes https://github.com/azerupi/mdBook/issues/392

### CODE REVIEW

**Comment by azerupi** [comment]
What does this print for the different cases? :)

**Comment by budziq** [comment]
"Playpen communication error"
"Playpen communication timeout"
"Playpen communication abort"

actually I did not find much interesting info in http://api.jquery.com/jquery.ajax/ that would allow to further differentiate.

**Comment by azerupi** [comment]
Seems good to me! :+1: 
We can always refine the messages over time. :)

Thanks!

**Comment by shepmaster** [comment]
> Playpen

FWIW, it's normally called the *playground*. "Playpen" was a Very Old name for it

**Comment by budziq** [comment]
> FWIW, it's normally called the playground. "Playpen" was a Very Old name for it

fixed in 
 https://github.com/azerupi/mdBook/commit/c36eca15c2f8d35005dd27571c22043b5bdac4ff

Thanks @shepmaster !

**Pull request merged**
