### PR TITLE
Fix the issue with pages named print not at the root

### LINKED ISSUE #435: Chapter named "print.html" brings up print dialog
A chapter like this:

    - [Formatted print](hello/print.md) 

when navigated to, brings up the print dialog.

I think we should check that it's the root's `print.html`, instead of any chapter named `print`.

### PR DESCRIPTION
**Pull request by azerupi**
Should fix #435

### CODE REVIEW

**Comment by steveklabnik** [comment]
Just tested this locally with RBE, works for me! 👍

**Comment by steveklabnik** [comment]
> The only problem that I see is that we have some styling regression in print media css (for some time since 0.0.23)

Is this a blocker then, or not?

**Comment by steveklabnik** [comment]
> The only problem that I see is that we have some styling regression in print media css (for some time since 0.0.23)

Is there a separate bug tracking this? If not, it should be opened!

**Comment by budziq** [comment]
> Is there a separate bug tracking this? If not, it should be opened!

Openend https://github.com/azerupi/mdBook/issues/444 :)

**Pull request merged**
