### PR TITLE
Bump version: 0.0.19 -> 0.0.20.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
I don't have crates.io publishing rights, so whoever merges this, please `cargo publish` :)

**Comment by azerupi** [comment]
I don't have my computer today, but I will try to release tomorrow if it's not already taken care of :)

**Comment by steveklabnik** [comment]
I will leave it to you @azerupi ; I am super busy today

**Comment by azerupi** [comment]
I published a new release, I used cargo release so I didn't merge this PR as it bumps the version number itself. :)

**Pull request closed without merging**
