### PR TITLE
add tooltip to icons

### LINKED ISSUE #388: Add tooltips to code buttons
image

Buttons on code blocks do not currently have tooltips explaining what they do. It would be great to add tooltips with a very short explanation of what the buttons do (couple of words) when hovering over them.

### PR DESCRIPTION
**Pull request by mockersf**
fixes #388
added titles to play/copy/reset, expand/collapse and sidebar/theme buttons

### CODE REVIEW

**Comment by budziq** [comment]
@mockersf Very cool! Could you also add tooltips to the next and prev buttons at the bottom of the page?

**Comment by mockersf** [comment]
Oh, didn't see those as there are already tooltips for them in browser, they were only missing in mobile.
I didn't copy the text as they mention using the arrow keys to navigate which may not be available on mobile.

**Comment by budziq** [comment]
back. Hmm it looks like the links in the navigation buttons are duplicated and the tooltips are set on the second pair of links which leaves the buttons without tooltips on chromium and firefox (both on linux)

**Comment by mockersf** [comment]
Yes, the mobile-nav-chapters class is displayed instead of nav-chapters if screen is less than 1250px wide. Both sets of links should have the title now.

**Comment by budziq** [comment]
Thanks @mockersf !

**Pull request merged**
