### PR TITLE
set up AppVeyor to test and deploy on Windows

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by azerupi** [comment]
Is this ready to merge?
To make sure I understand what this does: This tests windows builds, creates the artifacts and uploads them back to github?

**Comment by japaric** [comment]
> Is this ready to merge?

Not yet, I just noticed AppVeyor has some weird pipeline compared to Travis CI so the deploy part is not working as expected. I'll fix it in a bit.

> To make sure I understand what this does: This tests windows builds, creates the artifacts and uploads them back to github?

That's the intention. Normally, on pushes and new pull requests, it only tests on windows. And only when a new tag is pushed, it builds on release, zips and uploads the zipfiles to GitHub.

**Comment by azerupi** [comment]
Ok, let me know when I need to merge :)

**Comment by japaric** [comment]
Fixed the deploy issue. This is good to go now :D.

**Pull request merged**
