### PR TITLE
fixed `cargo build --features=regenerate-css` on win 10 / nightly

### PR DESCRIPTION
**Pull request by budziq**
fixes https://github.com/azerupi/mdBook/issues/342

@azerupi I finally had little time to tinker with win 10 box and fixed the long standing bug with `cargo build --features=regenerate-css`.
also added css regeneration build to appveyor.

### CODE REVIEW

**Comment by budziq** [comment]
appveyor nightly build fails illustrating the https://github.com/azerupi/mdBook/issues/342 issue.

**Comment by budziq** [comment]
@azerupi do you think it's ok to merge this one?

**Comment by azerupi** [comment]
Yes, I glanced over it and it looks fine (way better than before :wink: )

**Comment by budziq** [comment]
Thanks!

**Pull request merged**
